// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLddfJNtHR0B_7dqOeiF1X9bFEdGwE6FQ',
    appId: '1:455115475538:web:09dbde2eda4aca033ced8b',
    messagingSenderId: '455115475538',
    projectId: 'mynotes-2f91f',
    authDomain: 'mynotes-2f91f.firebaseapp.com',
    storageBucket: 'mynotes-2f91f.appspot.com',
    measurementId: 'G-QNQC7KDF1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnyjfu6j86y5rNaDKA7WXpP_VrNJGOiJA',
    appId: '1:455115475538:android:93731f65f64a9f723ced8b',
    messagingSenderId: '455115475538',
    projectId: 'mynotes-2f91f',
    storageBucket: 'mynotes-2f91f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcY_0quYot6ov9jwN8BsWAsrQbx8gNaTM',
    appId: '1:455115475538:ios:9bc8766b17088a1d3ced8b',
    messagingSenderId: '455115475538',
    projectId: 'mynotes-2f91f',
    storageBucket: 'mynotes-2f91f.appspot.com',
    iosClientId: '455115475538-gs2ekvo3pi26d6oa4fnp3gc3p13r3f5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcY_0quYot6ov9jwN8BsWAsrQbx8gNaTM',
    appId: '1:455115475538:ios:2f616e68ae0121073ced8b',
    messagingSenderId: '455115475538',
    projectId: 'mynotes-2f91f',
    storageBucket: 'mynotes-2f91f.appspot.com',
    iosClientId: '455115475538-sbo0elu7peqh2rhom6ueben85attk41u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
